version: "3.0"

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    links:
      - lain_db
    environment:
      LainRadioToken: ${LainRadioToken}

  lain_db:
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
