name: Deploy release to server
on: [push]
jobs:
  deploy:
    name: Deploy job
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        name: Deploying to server
        env:
          SERVER: ${{ secrets.SERVER }}
        run: ./ .github/scripts/deploy.sh $SERVER
