name: Deploy release to server
on: [push]

jobs:
  deploy:
    name: Deploy job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - shell: bash
        name: Deploying to server
        env:
          SERVER: ${{ secrets.SERVER }}
        run: |
          chmod +x ./scripts/deploy.sh
          ./scripts/deploy.sh
