name: Deploy release to server
on: [push]

jobs:
  deploy:
    environment:
      name: lain-radio-bot
    name: Deploy job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Deploying to server
        env:
          SERVER: ${{ secrets.SERVER }}
      - shell: bash
        name: SSH Step
        run: |
          chmod +x ./scripts/deploy.sh
          ./scripts/deploy.sh
