name: Deploy release to server
on: [push]

jobs:
  lain-radio-bot:
    environment:
      name: lain-radio-bot
    name: Deploy job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Deploying to server

      - uses: fifsky/ssh-action@master
        name: SSH step
        with:
          command: |
            cd /home/lainradio/Projects/lain-radio-bot
            ls -la
          host: ${{ secrets.SERVER }}
          user: ${{ secrets.USER }}
          pass: ${{ secrets.PASSWORD }}
