name: Deploy release to server
on: [push]

jobs:
  lain-radio-bot:
    environment:
      name: lain-radio-bot
    name: Deploy job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Deploying to server

      - shell: bash
        env:
          SERVER: ${{ secrets.SERVER }}
          MESSAGE: ${{ secrets.MESSAGE }}
        name: SSH Step
        run: |
          chmod +x ./scripts/deploy.sh
          ./scripts/deploy.sh
