name: Deploy release to server
on: [push]
jobs:
  deploy:
    name: Deploy job
    runs-on: ubuntu-latest
    steps:
      - name: Deploying to server
        env:
          SERVER: ${{ secrets.SERVER }}
        run: echo Working Action to deploy to "$SERVER"
